// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcrnkuxuolnpemekzfvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdjcm5rdXh1b2xucGVtZWt6ZnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTg4MDUsImV4cCI6MjA2NjQ5NDgwNX0.fOQMWdQBGGFrtcOdhTc38n3lmnFEiIsa_Wg-SAKJ83g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);